name: ${project.name}
main: net.plazmix.coreconnector.direction.bukkit.BukkitConnectorPlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}

author: ItzStonlex

depend: [CloudNet-Bridge]
